name: Preserve My Bouquet
favicon: null
layout_spectrum: 0.7512591206468642
typography_spectrum: 0.2727374585811049
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.629481102572754
  lightness: 0.434007307048887
  saturation: 0.29662409657612443
  rhythmicContrast: 0.0986808214802295
purpose: []
